services:
  - type: web
    name: sarva-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: TRANSCRIBE_PORT
        value: 5001
      - key: SARVAM_API_KEY
        sync: false # Requires manual entry in Render dashboard
